### ISSUE TITLE
Traceback from ext-smtp-realtime-stderr---supervisor.log

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#18]
Traceback (most recent call last):
  File "/opt/prodiguer/ops/venv/python/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/prodiguer/ops/venv/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/prodiguer/ops/jobs/mq/producer/__main__.py", line 119, in <module>
    _execute()
  File "/opt/prodiguer/ops/jobs/mq/producer/__main__.py", line 112, in _execute
    _execute_non_standard(producer)
  File "/opt/prodiguer/ops/jobs/mq/producer/__main__.py", line 90, in _execute_non_standard
    producer.execute(options.agent_limit)
  File "/opt/prodiguer/ops/jobs/mq/producer/ext_smtp_realtime.py", line 101, in execute
    mail.disconnect(imap_client)
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/utils/mail.py", line 67, in disconnect
    func()
  File "/opt/prodiguer/ops/venv/server/lib/python2.7/site-packages/imapclient/imapclient.py", line 504, in idle_done
    return self._consume_until_tagged_response(self._idle_tag, 'IDLE')
  File "/opt/prodiguer/ops/venv/server/lib/python2.7/site-packages/imapclient/imapclient.py", line 935, in _consume_until_tagged_response
    resps.append(_parse_untagged_response(line))
  File "/opt/prodiguer/ops/venv/server/lib/python2.7/site-packages/imapclient/imapclient.py", line 1065, in _parse_untagged_response
    assert text.startswith(b'* ')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by momipsl** [comment]
Extended error handling so as ignore this error which is raised when trying to close a connection that was not in idle mode.

**Comment by SebastienDenvil** [comment]
Ok to ignore it for now. But it is misleading to have an error one should ignore. This must be fix.
