### ISSUE TITLE
Issue with daemons after upgrading. Deamons not starting

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/prodiguer-docs#32]
Traceback (most recent call last):
  File "/opt/prodiguer/ops/venv/python/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/prodiguer/ops/venv/python/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/prodiguer/ops/jobs/mq/consumer/__main__.py", line 18, in <module>
    from prodiguer import config, cv, db, mq, rt
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/__init__.py", line 19, in <module>
    from prodiguer import api, cv, db, mq, utils
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/api/__init__.py", line 14, in <module>
    from prodiguer.api.app import run
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/api/app.py", line 19, in <module>
    from prodiguer.api import metric, monitoring, ops, utils
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/api/metric/__init__.py", line 14, in <module>
    from prodiguer.api.metric.add import AddRequestHandler
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/api/metric/add.py", line 19, in <module>
    from prodiguer.api.metric import utils
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/api/metric/utils.py", line 16, in <module>
    from prodiguer.db.mongo import dao_metrics as dao
  File "/opt/prodiguer/repos/prodiguer-server/src/prodiguer/db/mongo/dao_metrics.py", line 17, in <module>
    from metrics_formatter import hashifier
ImportError: No module named metrics_formatter

**Comment by momipsl** [comment]
The resolution of this problem is to edit the /opt/prodiguer/ops/config/mq-supervisord.conf file.  The daemons call the jobs directly and not via the shell and so therefore you need to set the python path correctly (this explains why this issue did not arise when testing the system from the command line).  You will observe that after the declaration of each daemon there is an instruction to initialise the python path for that daemon:
	environment=PYTHONPATH=/opt/prodiguer/repos/prodiguer-server/src
Each of these instructions (there are at least 4) need to be updated to the following:
	environment=PYTHONPATH=/opt/prodiguer/repos/prodiguer-server/src:/opt/prodiguer/repos/prodiguer-metrics-formatter
